### ISSUE TITLE
Current Address 0.0 0.0

### ISSUE THREAD

**Issue by tellfa** [prabhat1707/EasyWayLocation#1]
Hi,
thanks for this library dear.
i want use your library but when run application show me Current Address 0.0 0.0
and not show me my address info!

how can i fix it?

**Comment by tellfa** [comment]
When set location permission show me location info.
but why not show any dialog for get location permission?!

**Comment by prabhat1707** [comment]
thanks, @tellfa, locationOn method is just call back use position changed to get the location.


`@Override
    public void locationOn() {
        Toast.makeText(this, "Location ON", Toast.LENGTH_SHORT).show();
        easyWayLocation.beginUpdates();
        diff.setText(String.valueOf(EasyWayLocation.calculateDistance(28.626686, 77.026409, 28.626799, 77.033619)));
    }

    @Override
    public void onPositionChanged() {
        lati = easyWayLocation.getLatitude();
        longi = easyWayLocation.getLongitude();
        location.setText(EasyWayLocation.getAddress(this, lati, longi, false, true));
        latLong.setText(String.valueOf(lati) + "  " + String.valueOf(longi));
        Toast.makeText(this, String.valueOf(easyWayLocation.getLongitude()) + "," + String.valueOf(easyWayLocation.getLatitude()), Toast.LENGTH_SHORT).show();
    }`
