### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by behbudovusal** [prabhat1707/EasyWayLocation#11]

**Comment by behbudovusal** [comment]
@prabhat1707 ?

**Comment by prabhat1707** [comment]
sorry for delay @behbudovusal can u please share the log or scenario so, that I can fix this issue asap by EOD.

**Comment by behbudovusal** [comment]
@prabhat1707 nothing happen.It worked 1 week ago.Now not working.I log but nothing happen

**Comment by prabhat1707** [comment]
Mean while I am working can u check keys and other thing related to map

**Comment by prabhat1707** [comment]
@behbudovusal I just publish one update, please check.
