### ISSUE TITLE
Not working:(((

### ISSUE THREAD

**Issue by behbudovusal** [prabhat1707/EasyWayLocation#12]
override fun locationCancelled() {

    }

    override fun locationOn() {
    }

    override fun currentLocation(location: Location?) {

        data.append(location!!.latitude)
        data.append(" , ")
        data.append(location!!.longitude)
        lati = location.latitude
        longi = location.longitude
        Log.e("lat", lati.toString() + " " + longi)
        getLocationDetail!!.getAddress(location.latitude, location.longitude, "xyz")
    }

    override fun locationData(locationData: LocationData?) {
        Log.e("city", locationData?.city)
        binding.locationtxt.text = locationData?.city + " " + locationData?.country
    }

    fun permissionIsGranted(): Boolean {
        val permissionState = ActivityCompat.checkSelfPermission(
            this,
            Manifest.permission.ACCESS_COARSE_LOCATION
        )
        return permissionState == PackageManager.PERMISSION_GRANTED
    }

    private fun doLocationWork() {
        easyWayLocation.startLocation()
    }

    override fun onActivityResult(
        requestCode: Int,
        resultCode: Int,
        @Nullable data: Intent?
    ) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == LOCATION_SETTING_REQUEST_CODE) {
            easyWayLocation.onActivityResult(resultCode)
        }
    }

    private fun hideKeyboard() {
        // Check if no view has focus:v
        val view = currentFocus
        if (view != null) {
            val inputManager =
                getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
            inputManager.hideSoftInputFromWindow(
                view.windowToken,
                InputMethodManager.HIDE_NOT_ALWAYS
            )
        }
    }

    override fun onPause() {
        super.onPause()
        easyWayLocation.endUpdates()
    }

init{
   getLocationDetail = GetLocationDetail(this, this)
        easyWayLocation = EasyWayLocation(this, false, this)
        if (permissionIsGranted()) {
            doLocationWork()
        } else {
            // Permission not granted, ask for it
        }
    }
}

**Comment by prabhat1707** [comment]
you are doing this inactivity class or some other util class?

**Comment by prabhat1707** [comment]
no response closing it
