### ISSUE TITLE
How to temporary stop gettting current location in EasyWayLocation.

### ISSUE THREAD

**Issue by nayab01** [prabhat1707/EasyWayLocation#14]
Hello there,
I am using this library in my project but sometimes i need to change my current location so there is any way to stop getting current locatrion for some time if there is way plz let me know ASAP...

**Comment by prabhat1707** [comment]
yes, you can use ` easyWayLocation.endUpdates()`

**Comment by nayab01** [comment]
thank you so much, man!!!
