### ISSUE TITLE
Arc Route with all animation properties (Feature Request)

### ISSUE THREAD

**Issue by Attique033** [prabhat1707/EasyWayLocation#18]
Hi, library is awesome. works like charm. Can you please add the arc route and animation like Uber. i've seen it for ios but can't find any library for android. Thanks in advance

**Comment by prabhat1707** [comment]
Hi, thanks for the suggestion.
can you send me a screenshot of this and also if there are any ios lib there then same for ios also.

**Comment by Attique033** [comment]
Hi, below is link of library i used to create uber like animation, video recording is also [attached](https://drive.google.com/file/d/1uBn1HxCKtl8dfqN4X1YwTdLnIOyAsYFY/view?usp=sharing)
https://github.com/goldmoment/AnimatePolyline

**Comment by prabhat1707** [comment]
Hey, it look like when ride is not started then it show in arc animation and also in iOS link arc is not there is normal path like mine lib.

But I am looking into this and will update when it done for android .

**Comment by prabhat1707** [comment]
It done plz check new version
